In [2]:
import numpy as np
arr=np.array([10,20,30,40,50])
arr[0]

10

In [5]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix[1,2]

6

In [6]:
arr=np.array([0,1,2,3,4,5])
arr[1:4]

array([1, 2, 3])

In [7]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [8]:
arr=np.array([10,15,20,25,30])
arr[arr>20]

array([25, 30])

In [9]:
arr=np.array([10,20,30,40,50])
indices=[0,2,4]
arr[indices]

array([10, 30, 50])

In [10]:
arr=np.array([1,2,3,4,50])
arr[[0,2,4]]

array([ 1,  3, 50])

In [14]:
array=np.array([1,2,3,4])
array[1:3]=99
array

array([ 1, 99, 99,  4])