In [2]:
import numpy as np
p=[[1,2],[5,8]]
q=[[9,6,],[4,2]]
dot_ans=np.dot(p,q)
dot_ans

array([[17, 10],
       [77, 46]])

In [3]:
p=[[1,2],[5,8],[9,11]]
q=[[9,6,8],[4,2,3]]
print(p)
print(q)
dot_ans=np.dot(p,q)
dot_ans

[[1, 2], [5, 8], [9, 11]]
[[9, 6, 8], [4, 2, 3]]


array([[ 17,  10,  14],
       [ 77,  46,  64],
       [125,  76, 105]])

In [5]:
matrix=np.array([[1,2,3],[4,5,6]])
transpose_matrix=matrix.T
transpose_matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
matrix=np.array([[1,2,3],[4,5,6],[8,7,9]])
inverse_matrix=np.linalg.inv(matrix)
inverse_matrix

array([[-0.33333333, -0.33333333,  0.33333333],
       [-1.33333333,  1.66666667, -0.66666667],
       [ 1.33333333, -1.        ,  0.33333333]])

In [8]:
p=np.array([[1,2],[5,8]])
eigenvalues,eigenvectors=np.linalg.eig(p)
print("Eigenvalues",eigenvalues)
print("Eigenvectors",eigenvectors)

Eigenvalues [-0.21699057  9.21699057]
Eigenvectors [[-0.85427457 -0.23649365]
 [ 0.51982205 -0.97163304]]


In [10]:
arr=np.array([1,4,-9,0,-3])
result=np.where(arr<0,0,arr)
print(result)

[1 4 0 0 0]


In [24]:
arr=np.array([10,15,20,25,30])
indices=np.where(arr>20)
print(indices)
print(arr[indices])


(array([3, 4]),)
[25 30]


In [25]:
arr=np.array([2,2,4,3,3,7,5,5])
unique_elements=np.unique(arr)
unique_elements

array([2, 3, 4, 5, 7])

In [26]:
arr=np.array([8,2,4,1,3,9,7,6,5])
sarr=np.sort(arr)
sarr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
x = np.nan
print("isnan:", np.isnan(1),"\n")
print("isnan:", np.isnan(x),"\n")

isnan: False 

isnan: True 



In [36]:
arr1=np.array([8,2,4,1,3])
list=[4,2,3]
arr=np.isin(arr1,list)
arr

array([False,  True,  True, False,  True])