In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [2]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[4:])

[5 6 7 8]


In [3]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[:4]

array([1, 2, 3, 4])

In [6]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[-3:-1]

array([6, 7])

In [7]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[1:2:4]

array([2])

In [8]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[::4]

array([1, 5])

In [17]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
# in print 1 represent the row here we have 2 rows 0 and 1 0=1,2,3,4,5 and 1=6,7,8,9,10
print(arr[1,0:4])

[6 7 8 9]


In [16]:
arr=np.array([[1,2,3,4],[5,7,10,8]])
# here the 2 in the slicing represent the 2nd element from both rows
arr[0:3,2]

array([2, 7])

In [18]:
arr=np.array([[1,2,3,4],[5,7,10,8]])
# here 0:2 represent the rows ie., 0,1 rows and exclude 2nd row and 1:4 represents the coloumn in the row
arr[0:2,1:4]

array([[ 2,  3,  4],
       [ 7, 10,  8]])

In [20]:
arr = np.array (['apple','bananaa','cherry'])
# output will be in unicode and the number near U represent the largest length in the array
print(arr.dtype)

<U7


In [26]:
arr=np.array([1,2,3,4],dtype='S')
# to create a string datatype
arr

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [27]:
arr=np.array([1.1,2.1,3.1])
# astype used to convert one datatype to another
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)


[1 2 3]
int32


In [28]:
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('b')
newarr
newarr.dtype

dtype('int8')