In [1]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
scalar=10
result=array+scalar
result

array([[11, 12, 13],
       [14, 15, 16]])

In [6]:

x=np.array([[1,2],[4,5]])
y=np.array([[8,7],[9,6]])
print(np.add(x,y))
print(np.subtract(x,y))
print(np.divide(x,y))
print(np.multiply(x,y))

[[ 9  9]
 [13 11]]
[[-7 -5]
 [-5 -1]]
[[0.125      0.28571429]
 [0.44444444 0.83333333]]
[[ 8 14]
 [36 30]]


In [7]:
x=np.array([[1,2],[4,5]])
y=np.array([[8,7],[9,6]])
print(np.multiply(x,y))
# dot operation is used to perform matrix multiplication
print(np.dot(x,y))

[[ 8 14]
 [36 30]]
[[26 19]
 [77 58]]


In [10]:
x=np.array([[1,2],[4,5]])
y=np.array([[8,7],[9,6]])
print(np.sqrt(x))
print(np.sum(y))
print(np.sum(y,axis=0))
# when axis is 0 it add coloumn vice and for axis=1 it add the rows
print(np.sum(y,axis=1))

[[1.         1.41421356]
 [2.         2.23606798]]
30
[17 13]
[15 15]
