In [2]:
import numpy as np
a= np.array([5,72,13,100])
b= np.array([2,5,10,30])
add_ans=np.add(a,b)
add_ans

array([  7,  77,  23, 130])

In [3]:
a= np.array([5,72,13,100])
b= np.array([2,5,10,30])
sub_ans=np.subtract(a,b)
sub_ans

array([ 3, 67,  3, 70])

In [4]:
a= np.array([5,72,13,100])
b= np.array([2,5,10,30])
mult_ans=np.multiply(a,b)
mult_ans

array([  10,  360,  130, 3000])

In [5]:
a= np.array([5,72,13,100])
b= np.array([2,5,10,30])
div_ans=np.divide(a,b)
div_ans

array([ 2.5       , 14.4       ,  1.3       ,  3.33333333])

In [6]:
a= np.array([5,3,10,8])
b= np.array([2,3,2,4])
pow_ans=np.power(a,b)
pow_ans

array([  25,   27,  100, 4096])

In [9]:
import numpy as np
a= np.array([5,19,106,8])
b= np.array([2,4,9,5])
mod_ans=np.mod(a,b)
mod_ans

array([1, 3, 7, 3])

In [30]:
arr=[20,2,.2,10.4]
print("\n Sum of the arr:",np.sum(arr))
sum_ans=np.sum(arr)
print(np.sum(arr,dtype=np.uint8))
print(np.sum(arr,dtype=np.float32))
print(np.sum(arr).dtype==np.uint)
print(np.sum(arr).dtype==np.float64)
sum_ans.dtype


 Sum of the arr: 32.6
32
32.6
False
True


dtype('float64')

In [33]:
arr=[[14,17,12,33,44],[15,6,27,8,17],[23,2,54,1,4]]
print("\n Sum of arr:",np.sum(arr))
print(np.sum(arr,axis=0))
# axis=0 means it takes the sum of the elements in coloumn eg:here it takes the sum of 14+15+23=5
print(np.sum(arr,axis=1))
# axis=1 means it takes the sum of the elements in row eg:here it takes the sum of 14 +17+12+33+44=120
print(np.sum(arr,axis=0,keepdims=True))
# keepdims provide the same dimension as the input here it's in 2D


 Sum of arr: 277
[52 25 93 42 65]
[120  73  84]
[[52 25 93 42 65]]


In [34]:
import numpy as np
arr=[20,2,7,1,34]
print("arr",arr)
print(np.mean(arr))

arr [20, 2, 7, 1, 34]
12.8


In [35]:
a=[20,2,7,1,34]
b=[12,4,25,7,5]
num=np.maximum(a,b)
print(num)

[20  4 25  7 34]


In [36]:
a=[20,2,7,1,34]
b=[12,4,25,7,5]
num=np.minimum(a,b)
print(num)

[12  2  7  1  5]
