In [7]:
# import numpy as np
from numpy import random
x=random.randint(100)
print(x)

85


In [9]:
x=random.rand()
x

0.5333673698373028

In [11]:
x=random.randint(100,size=(5))
x

array([12,  6, 37, 81, 75], dtype=int32)

In [12]:
x=random.randint(100,size=(3,5))
print(x)

[[38 95 99 91 47]
 [51 48 45 70 22]
 [98  9 86  9 99]]


In [13]:
x=random.rand(5)
x

array([0.03228657, 0.0839662 , 0.08179554, 0.79759519, 0.85838369])

In [73]:
x=random.choice([3,5,7,9])
print(x)

9


In [32]:
from numpy import random
x=random.choice([3,5,7,9,5,6], size=(2,4))
# it takes random 4 elemens from array here the dimenssion given as 2 so 2D array
print(x)

[[5 3 9 9]
 [5 7 5 5]]


In [45]:
import random
for i in range(2):
    print(random.randint(1,1000))
for i in range (2):
    random.seed(0)
    print(random.randint(1,1000))

395
777
865
865


In [41]:
arr=np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

[3 5 1 4 2]


In [39]:
arr=np.array([1,2,3,4,5])
permuted_arr=np.random.permutation(arr)
print(arr)
print(permuted_arr)
shuffle_range=np.random.permutation(5)
print(shuffle_range)

[1 2 3 4 5]
[3 1 4 2 5]
[1 2 0 3 4]


In [69]:
import random
for i in range(5):
    print(random.randint(1,10))
for i in range (5):
    random.seed(0)
    print(random.randint(1,10))

7
1
5
9
8
7
7
7
7
7
