In [8]:
import numpy as np
array=np.array ([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
n=array.size
reshaped1=array.reshape((4,4))
reshaped2=np.reshape(array,(2,8))
print(reshaped1)
print(reshaped2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [11]:
array=np.array ([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
reshaped=array.reshape(2,2,4)
reshaped

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [12]:
gf=np.array([1,2,3,4,5,6])
gf.resize(2,3)
gf

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
gf=np.array([1,2,3,4,7,6,5])
gf.resize(3,4)
# if the there is no number to be filled it will fill with 0s
gf

array([[1, 2, 3, 4],
       [7, 6, 5, 0],
       [0, 0, 0, 0]])

In [18]:
array=np.array ([1,2,3,4,5,6,7,8,9])
reshaped=array.reshape((3,3))
print(reshaped)
flatted=reshaped.flatten()
print(flatted)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [20]:
arr=np.array([1,2,3,4,5,6,7])
array=np.array_split(arr,3)
array

[array([1, 2, 3]), array([4, 5]), array([6, 7])]